### ISSUE TITLE
Userstory 6 - Comment function under the movie details

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#13]
## Value Proposition

**As a** user
**I want to** i would like to be able to add comments and see the ratings of others
**So that** i can exchange ideas about the films with others

## Description

![Userstory 6 - Kommentare](https://github.com/CarstenJahnke/MCU-App/assets/130060363/68ec628c-d5e0-44f4-b0a8-a22add9ccab7)

## Acceptance Criteria

- [ ] so that the users can exchange information about the films, a comment function is required

## Tasks

- [ ] create a feature branch
- [ ] create a comment card, with input fields for the user's name and comment and a submit button
- [ ] Show all comments under the comment input field
- [ ] Data are stored in `LocalStorage`
- [ ] output from `LocalStorage` to the movie details page
