### ISSUE TITLE
Userstory 7 - Favorite Button

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#14]
## Value Proposition

**As a** user
**I want to** be able to mark my favorite movies
**So that** i can quickly find my favorite movies again

## Description

![Userstory 7 - Favoriten](https://github.com/CarstenJahnke/MCU-App/assets/130060363/d12d42f0-b712-4dae-ab4b-a7720bc56d79)

## Acceptance Criteria

- [ ] Each film has a bookmark button
- [ ] Each bookmark button can be clicked
- [ ] After each button has been clicked there is an optical change of the button.

## Tasks

- [ ] Create a new branch "favorite_button" 
- [ ] Add a "Favorite" property for each movie, with a dummy data array
- [ ] Create a FavoriteButton component to represent the Favorite button for a movie
- [ ] Design the FavoriteButton to visually indicate whether the button is favorited or not (e.g., using svg-image)
- [ ] Implement toggling the favorite status of a movie when the FavoriteButton is clicked
- [ ] Integrate the FavoriteButton component with the FilmList component to allow users to mark movies as favorites.
- [ ] Favorite status should be stored in LocalStorage.
- [ ] Style the "FavoriteButton" with CSS .

**Comment by CarstenJahnke** [comment]
Thx @MariaRiosNavarro 😄👍

**Comment by MariaRiosNavarro** [comment]
🚀🚀🚀
