### ISSUE TITLE
Userstory 8 - Favorites Page

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#15]
## Value Proposition

**As a** user
**I would like** to easily have the ability to view and manage my favorite movies
**So that** i can see only my favorite movies on the page

## Description

![Userstory 8 - Favoriten Seite](https://github.com/CarstenJahnke/MCU-App/assets/130060363/e46112f2-caa4-4870-9351-f6e0212ac86b)

## Acceptance Criteria

- [ ] By filtering directly at the top of the header, I can see all my favorite movies
- [ ] Now I can see all my previously favorited movies 
- [ ] If I don't have any movies favorited, I can see "You don't have any favorite movies yet"
- [ ] To get back to the overview, I can easily change the filter again at the top.

## Tasks

- [ ] Create a new branch "favorite_feature"
- [ ] Create a "Favorites" component to display all the favorite movies in the filter
- [ ] Create a file "favorites.js" 
- [ ] Include the filter in the filter bar at the header
- [ ] If no movies are favorited, display the message "You don't have any favorited movies yet" on the filter page
- [ ] Basic CSS to make the "favorites" readable

**Comment by MariaRiosNavarro** [comment]
Great job
