### ISSUE TITLE
Userstory 9 - Mark movies as watched 

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#19]
## Value Proposition

**As a** user
**I would like** to mark the movies as "already seen 
**So i can** see better which movies i have not seen yet

## Description

![Userstory 9 - Gesehene Filme](https://github.com/CarstenJahnke/MCU-App/assets/130060363/0af4817d-3b87-4294-9aa6-eb28c1eb061b)

## Acceptance Criteria

- [ ] Each movie has a "seen" button
- [ ] Each seen button can be clicked on
- [ ] After clicking each button there is a visual change of the button.

## Tasks

- [ ] Create a new branch "seen_button"
- [ ] Add a "Seen" property for each movie, with a dummy data array
- [ ] Create a SeenButton component to represent the "Seen" button for a movie
- [ ] Design the SeenButton to visually indicate whether the button is marked as seen or not (e.g., using svg-image) 
- [ ] Implement toggling the seen status of a movie when the SeenButton is clicked
- [ ] Integrate the SeenButton component with the FilmList component to allow users to mark movies as Seen.
- [ ] The Seen status should be stored in LocalStorage.
- [ ] Style the "SeenButton" with CSS .

**Comment by Airglow98** [comment]
Nice description! I absolutely know what you will do without knowing your whole project.
