### ISSUE TITLE
Userstory 1.1 - Basic Structure

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#2]
## Value Proposition

**As a** User
**I want to** get the films from the MCU (Marvel Cinematic Universe)
**so that** i can see all the films from the MCU
​

## Description

![Wireframe - Userstory 1 1 Grundgerüst](https://github.com/CarstenJahnke/MCU-App/assets/130060363/efbf97b7-df4f-474d-891a-341986a7e3d7)

Userstory 1.1 - Basic Structure

- fetching the API from all Films (Poster, titles, descriptions, release year, ratings, ...)
- and push it in a list on the Homepage​

## Acceptance Criteria

- [ ] all MCU-films should be displayed on the Homepage
      ​

## Tasks

- [ ] Fetch the API from the Database
- [ ] Put the data in a list on the homepage

**Comment by FelineHuhn** [comment]
Hey Carsten, nice start 🎉 I have some suggestions for you: 

Value proposition: 
- i think the wording is not so accurate, since you don't "get" the films as a user. I would maybe change it to something like
- 
**As a** user
**I want to** see a list of all Marvel films
**So that** I can browse through the films to get inspiration, which one I could watch

Description/Wireframe: 
- I would think a headline would be nice, too. 
- Maybe you could show the films and it's information as cards or something?
- The written description "Userstory 1.1 - basics Structure ..." part was a little bit confusing for me, i think you could remove it, when you have a clearly formulated wireframe, or?  

Acceptance criteria: 
- the criteria should be more specific e.g. like: 
   - the headline is "Marvel Cinematic Universe Films"
   - films are displayed as cards in a list 
   -  the film cards include the title, year, description, rating, reviews, plakat

Tasks: 
- also the tasks should be more specific e.g. like: 
  - create a feature branch
  - fetch all movies from API 
  - add a headline
  - create `Movies` component to render a list
  - create `Movie` component
  - use the `Movie` component to display the fetched data in the `Movies` component
  
  
Last I ask me, if it be much easier to make two user stories out of this one user story. since it has quite a large scope for the first user story. You first could built the movie list with mock data and that fetch the data of the api in a second user story and replace the mock data than. What do you think about it?

**Comment by FelineHuhn** [comment]
Great progress Carsten 🎉 I only have some tiny suggestions left: The lines below the wireframe "Userstory 1 - Basic Structure [...] list on the Homepage" should be removed, since we don't need that, or?

I think there could be a bit more suitable wording for your acceptance criteria, like: 
- movies are displayed as cards in a list
- the movie cards include the poster as image, the title and the release year

For the tasks i suggest you, to change the last two points to
- use `Movie` component to display the fetched movie data 
- add minimal styling (maybe instead of center the list, so you have more flexibility, or?)

By the way: I know i was the one who gave you the suggestion, but when i think about it again, you actually don't really need a `Movies` component, since you can render the `Movie` component just in an `ul` tag. With a component it works too, but thats up to you.
