### ISSUE TITLE
Userstory 10 - Watched Movies

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#21]
## Value Proposition

**As a** user
**I would like** to easily have the ability to view and manage my watched movies
**So that** i can see only my watched movies on the page

## Description

![Userstory 10 - Gesehene Filme Seite](https://github.com/CarstenJahnke/MCU-App/assets/130060363/e6170a2a-eb51-4e8b-adc2-a6dab827f1d6)

## Acceptance Criteria

- [ ] By filtering directly at the top of the header, I can see all my watched movies
- [ ] Now I can see all my previously watched movies 
- [ ] If I don't have any movies watched, I can see "You don't have any watched movies yet"
- [ ] To get back to the overview, I can easily change the filter again at the top.

## Tasks

- [ ] Create a new branch "watched_movies_page"
- [ ] Create a "Watched" component to display all the watched movies in the filter
- [ ] Create a file "watched.js" 
- [ ] Include the filter in the filter bar at the header
- [ ] If no movies are watched, display the message "You don't have any watched movies yet" on the filter page
- [ ] Basic CSS to make the "watched" readable

**Comment by matschi3** [comment]
LGTM! nice and small US
