### ISSUE TITLE
Userstory 11 - Toastify Message

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#22]
## Value Proposition

**As a** user
**I would like** to see a message when i have added or removed a movie
**So that** i can better see if the add has worked

## Description

![Userstory 11 - Gesehene Filme Seite](https://github.com/CarstenJahnke/MCU-App/assets/130060363/64ddd50f-4ea9-43e4-a9c8-ac15c4cfce9b)

## Acceptance Criteria

- [ ] by clicking on the favorites button, a movie is added to the favorites list
- [ ] this is then indicated by a small short message 
- [ ] in the upper right corner for a few seconds

## Tasks

- [ ] Create a new "toastify-message" branch
- [ ] Create components to display favorite and watched movies via toastify message
- [ ] Add some styling

**Comment by matschi3** [comment]
i assume the user gets different msg depending on add and delete.
Clean and easy US 🚀
