### ISSUE TITLE
Userstory 12 - Quiz

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#26]
## Value Proposition

**As a** user I would like some entertainment in the form of a quiz
**I want to** to answer questions about the MCU
**in order to** reinforce my knowledge about the MCU
​

## Description

![Userstory 12 - Quiz](https://github.com/CarstenJahnke/MCU-App/assets/130060363/69c516c3-a15b-41ba-a724-f394158439b0)

## Acceptance Criteria

- [ ] On the quiz page you can answer various random questions
- [ ] four different answer options are offered, of which only one is correct
- [ ] the correct answer is marked green
- [ ] the wrong answers are marked red
- [ ] stopwatch runs after the start
- [ ] results are displayed with stopped time and correct and wrong answer number
- [ ] with a restart button you can start the quiz again from the beginning
      ​

## Tasks

- [ ] Create a quiz start page with start button and back button
- [ ] 3 seconds timer until the quiz starts
- [ ] Create and embed quiz questions
- [ ] Randomly generate quiz questions
- [ ] create 4 answer options as button
- [ ] Color correct answer green after click
- [ ] Color wrong answers red after click
- [ ] stop after 10 questions
- [ ] show result page with number of correct and wrong answers
- [ ] show stopped time on result page
- [ ] create a restart button to restart the quiz

**Comment by dimitriosxmi** [comment]
## LGTM Nice US bro! 🎉
