### ISSUE TITLE
Userstory 13 - Link to Reviews

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#32]
## Value proposition

**As** a user, I would like to link to reviews of the movies
**I would like** to be able to submit and view a rating there as well
**To be able** to share my recommendation

## Description

![Userstory 13 - Link zu Bewertung](https://github.com/CarstenJahnke/MCU-App/assets/130060363/9598a432-ab7e-4d4b-9907-0a01f0da49cb)

## Acceptance criteria

- [ ] On the Movie Details Page the ratings card should be clickable      

## Tasks

- [ ] Create a new feature branch
- [ ] Link the ratings card with the corresponding page from the TMDB
