### ISSUE TITLE
Userstory 2 - Header / Footer

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#5]
## Value Proposition

**As a** user
**I want to** see a header and a footer for the navigation  
**So that** i can use the navigation in the next step
​

## Description

![Wireframe](https://github.com/CarstenJahnke/MCU-App/assets/130060363/0f88501b-f277-4624-8c37-a2a542aba517)

## Acceptance Criteria

- [ ] Header with Title
- [ ] Footer for the navigation

## Tasks

- [ ] create a feature branch
- [ ] add a header
- [ ] add the title in the header
- [ ] add a footer

**Comment by RonnySteady** [comment]
Hey Carsten, 

in the value proposition you say that you want to jump back AND FORTH but theres only a back button in your wireframe, in criteria and tasks, do you need a forward button in this screen?

Also "componence" should be named "component" ;-)

Cheers, Ronald

**Comment by FelineHuhn** [comment]
Hey Carsten, nice progress 🎉

I would suggest you to change your value proposition to something like "so that the application is structured clearer and I can click through it faster", since it's not just about jumping back, but also about getting there, right?

To your wireframe: Wouldn't it be more descriptive for jumping in different pages to implement a navigation like that: 
![mcu](https://github.com/CarstenJahnke/MCU-App/assets/112863528/8687a832-4cd2-4c93-9af7-dc989efd4146)
And i think a descriptive headline would be great for a good structure of your pages. What I mean, instead of only displaying the app title you could implement a dynamic headline in the header, like "Marvel films" on the movies page and "Film Details" on the details page, what do you think about that? 

The acceptance criteria could be less technical but more descriptive something like: 
- each page has a header at the top
- the header is displaying the App title (and the page headline?)
- each page has a navigation at the bottom
- the navigation has a list icon (or what else?)
- the list icon navigates to the movies page

The tasks could also a little bit more specific. Some suggestions for that e.g.: 
- create `Header` component
  - add header
  - add app title 
  - add logic to display on each page the corresponding headline
- create `Footer` component
  - add navigation
  - add list icon as link with logic to navigate to movies page on click
- use the `Header` to display the header on each page
- use the `Footer` to display the navigation on each page
- remove previous headlines
- remove "back to the startpage" button from the details page

**Comment by FelineHuhn** [comment]
And sorry for the wrong app title, of course 
##Marvelous Cinematic Unisearch

**Comment by FelineHuhn** [comment]
Hey Carsten, nice progress 😊. I have some more suggestions for you: 

Since you probably don't add a navigation now, please remove this feature from your value proposition and acceptance criteria.

In your wireframe you pictured the back button inside your `Header` component, right? If you want to implement it like this (technically it would be easier to implement it on the page below the `Header`) you should mention it in the acceptance criteria and tasks accordingly. 

In the acceptance criteria, your wording of "create a ... component" should be removed, since it is a technical task, wich is better placed in the tasks section (and you already mention it in the tasks). 

Maybe a little explanation to make the difference between acceptance criteria and tasks a little clearer: 
- In the acceptance criteria you describe, what the user should see (not from the developer view)
- In the tasks you describe , what you have to do technically step by step, to comply the acceptance criteria
