### ISSUE TITLE
Userstory 3 - Filmdetailspage

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#6]
## Value Proposition

**As a** user
**I want to** click on each poster  
**So that** i can get more information about film
​

## Description

![Userstory 3 - Filmdetails](https://github.com/CarstenJahnke/MCU-App/assets/130060363/4d9ee039-93b5-4569-85f1-0c5315d7a389)

## Acceptance Criteria

- [ ] Details page for each film with description, cast and reviews about the film

## Tasks

- [ ] create a feature branch
- [ ] add a page for each film created by ID
- [ ] add the poster, title with year, description and the reviews 
- [ ] add a navigation at the footer

**Comment by ThysBat** [comment]
Nice Wireframes, very easy to understand!
Regarding your acceptance criteria and tasks I see some differences there. In you acceptance criteria you stated you have to show the cast, but you don't mention that in your tasks. While in your tasks you mention details that are not in your acceptance criteria. So maybe you want to make sure, that those cover the same content.
Also I would add the back button in your acceptance criteria and which function it has.

**Comment by ThysBat** [comment]
And what is also not really clear to me is what you mean with automatically generated pages. Maybe what you are looking for are dynamic routes?

**Comment by CarstenJahnke** [comment]
Thanks a lot 😊
