### ISSUE TITLE
Userstory 4 - Phase Cards

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#7]
## Value Proposition

**As a** user
**I like to** see an overview of all movies of the Marvel Cinematic Universe displayed in the order of the phases
**So that** I can easily identify what phase any movie belongs to

## Description

![Userstory 4 - Container](https://github.com/CarstenJahnke/MCU-App/assets/130060363/78bb89f2-064f-4d01-abec-a6ef541dd0bd)

## Acceptance Criteria

- [ ] if the user opens the app, he sees all films sorted in the respective phases
- [ ] the phases are sorted by release date, starts with the first phase in 2008
- [ ] and the movies are sorted in the respective containers by release date (e.g. _Iron Man 1 (2008)_ to _The Avengers (2012)_ 
- [ ] for a better UX the phases are shown in a scrollable list

## Tasks

- [ ] create a feature branch
- [ ] create a `Container` componence wich called _"phases"_ (for example "_Phase 1_", "_Phase 2_", etc.)
- [ ] sort the movies by release in phases in their right cards

**Comment by actyvystom** [comment]
Hi Carsten,
your **value proposition** syntactically implies that the user gets some kind of overview and can assign movies etc. to these _phases_. Is that really what you want to cover in this user story? 

As far as I understood your project idea, I assume that it would be a first step to give a predefined version of these phases and use them as some kind of (visual and logical) container to display movies belonging to the corresponding phase. 

In both cases your acceptance criteria lack a clear and detailed description of your feature (reads more like a task item). Try to imagine what the user would see on the screen and describe the elements and their UX in detail (_e.g. the phases are shown in a scollable list_). And there will be definitely more than one acceptance criteria ;)

Concerning your **task list** at least a movie component is also missing as you are referring sort the movies.

Cheers, Thomas

**Comment by dimitriosxmi** [comment]
## LGTM mostly understandable and clear!
Apart from a bit of confusion of your
**Value PropositionValue Proposition**
stating
_"So that I can better assign them all to the phases​"_
speaking of the User's perspective and not the developer's perspective, it implies that the user will be assigning something over your WebApp's UI, but I believe you were writing this from the developer's perspective, for which case I would suggest
changing the text

from
_So that I can better assign them all to the phases​_
to
_So that I can easily identify what phase any movie belongs to_
👆  I believe this would be more from the "User" perspective and relevant to your described goal 😊
