### ISSUE TITLE
Userstory 5 - Sort by ...

### ISSUE THREAD

**Issue by CarstenJahnke** [CarstenJahnke/MCU-App#8]
## Value Proposition

**As a** user
**I want to** sort the movies by release date or chronological order
**So that** so i can see faster in which order i have to watch the movies

## Description

![Userstory 5 - Sortierung](https://github.com/CarstenJahnke/MCU-App/assets/130060363/4959023a-c058-45d8-bfaf-11a13844a173)

## Acceptance Criteria

- [ ] if the user wants to watch the movies in chronological order, he can see the correct order via a dropdown menu
- [ ] the same applies to the order according to published phases

## Tasks

- [ ] create a feature branch
- [ ] create a dropdown menu with two componence _"Chronologischen Reihenfolge"_ and _"Sortiert nach Phasen"_
- [ ] sort the `Card` components by phase if the _"Sortiert nach Phasen"_ is active by the dropdown menu
- [ ] sort the `Card` components by chronological order if _"Chronologischen Reihenfolge"_ is active by the dropdown menu
- [ ] for chronological order, a scrollable timeline must be added with the respective year of action

**Comment by dimitriosxmi** [comment]
## LGTM clear and straight to the point!
Note:
What I will say is probably just a personal preference, but the last task
aka.:
_"for chronological order, a scrollable timeline must be added with the respective year of action"_

sounds to my ear more like an acceptance criteria
I'd recommend putting that to the list of acceptance criteria
and instead put in the tasks something like:

_ensure that the `Chronological order` dropdown option is sorted by the `year of action`_
